name: PHP Static Analysis
on: [push, pull_request]
jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: intl
          tools: phpstan

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: composer install --prefer-dist

      - name: Run phpstan
        run: phpstan analyse -c phpstan.neon.dist --level=8 src/ tests/