name: CI

on:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          directories: src/ tests/
          level: 8
          phpstanVersion: ^0.12